const QUESTIONS=[
{n:1,q:"Allah kimdir?",a:"Allah birdir, eşi ve benzeri yoktur. O, bütün varlıkların yaratıcısı ve Rabbidir.",langs:["Allah kimdir?","Who is Allah?","Wer ist Allah?","Кто такой Аллах?","Allah kî ye?","Qui est Allah ?","¿Quién es Allah?","مَن هو الله؟"]},
{n:2,q:"Müslüman ne demektir?",a:"Allah'a teslim olan, O'na iman eden ve İslam'ın hükümlerini kabul eden kişidir.",langs:[]},
{n:3,q:"İslam ne demektir?",a:"Allah'ın birliğini kabul etmek, O'na teslim olmak ve O'nun bildirdiği dine uymaktır.",langs:[]},
{n:4,q:"İmanın anlamı nedir?",a:"Allah'ın bildirdiği hakikatleri kalp ile tasdik etmek ve bunlara iman etmektir.",langs:[]},
{n:5,q:"Kelime-i şehadet nedir?",a:"Allah'tan başka ilah olmadığına ve Muhammed'in Allah'ın kulu ve elçisi olduğuna şahitlik etmektir.",langs:[]},
{n:6,q:"Tevhid nedir?",a:"Allah'ın zatında, sıfatlarında ve fiillerinde bir ve eşsiz olduğuna inanmaktır.",langs:[]},
{n:7,q:"Şirk nedir?",a:"Allah'a zatında, sıfatlarında veya ibadetinde ortak koşmaktır.",langs:[]},
{n:8,q:"Allah'ın sıfatları neden önemlidir?",a:"Allah'ı doğru tanımaya ve O'na uygun şekilde iman etmeye yardımcı olur.",langs:[]},
{n:9,q:"İbadet nedir?",a:"Allah'ın rızasını kazanmak amacıyla yapılan, dinen meşru olan kulluk ve güzel davranışların bütünüdür.",langs:[]},
{n:10,q:"İhlas nedir?",a:"İbadeti yalnız Allah'ın rızası için yapmaktır.",langs:[]},
{n:11,q:"Niyet nedir?",a:"Bir işi hangi amaçla yaptığını kalben belirlemektir.",langs:[]},
{n:12,q:"Farz nedir?",a:"Dinin kesin delille yapılmasını emrettiği şeydir.",langs:[]},
{n:13,q:"Vacip nedir?",a:"Hanefî mezhebinde yapılması güçlü delille gerekli görülen dinî görevdir.",langs:[]},
{n:14,q:"Sünnet nedir?",a:"Hz. Peygamber'in sözleri, fiilleri, onayları ve yaşayış biçimidir.",langs:[]},
{n:15,q:"Helal ve haram ne demektir?",a:"Helal dinen yapılmasına izin verilen; haram ise kesin olarak yasaklanan şeydir.",langs:[]},
{n:16,q:"Temizlik neden önemlidir?",a:"İslam temizlik ve taharete önem verir; ibadetlerin bir kısmı temizlik şartına bağlıdır.",langs:[]},
{n:17,q:"Abdest nedir?",a:"Namaz gibi bazı ibadetler için belirli organları usulüne uygun olarak yıkamak veya meshetmektir.",langs:[]},
{n:18,q:"Gusül nedir?",a:"Bütün bedenin, dinen belirlenen şekilde temizlenmesidir.",langs:[]},
{n:19,q:"Namaz nedir?",a:"Belirli vakitlerde, belirli şart ve rükünlerle Allah'a yapılan temel ibadetlerden biridir.",langs:[]},
{n:20,q:"Namazın farzları nelerdir?",a:"Hanefî ilmihal düzeninde namazın dışındaki ve içindeki farzlar belirli şart ve rükünler halinde ele alınır.",langs:[]},
{n:21,q:"Namaz vakitleri nelerdir?",a:"Sabah, öğle, ikindi, akşam ve yatsı olmak üzere beş vakit namaz vardır.",langs:[]},
{n:22,q:"Ezan nedir?",a:"Namaz vaktinin girdiğini bildiren ve cemaati namaza çağıran dinî çağrıdır.",langs:[]},
{n:23,q:"Cemaatle namazın önemi nedir?",a:"Müslümanların birlik ve beraberliğini güçlendirir ve cemaat ibadetini teşvik eder.",langs:[]},
{n:24,q:"Kur'an nedir?",a:"Allah'ın Hz. Muhammed'e vahiy yoluyla gönderdiği son ilahî kitaptır.",langs:[]},
{n:25,q:"Kur'an neden okunur?",a:"Allah'ın kelamını öğrenmek, hidayet ve öğüt almak ve ibadet etmek için okunur.",langs:[]},
{n:26,q:"Vahiy nedir?",a:"Allah'ın peygamberlerine bildirdiği ilahî mesajdır.",langs:[]},
{n:27,q:"Peygamber kimdir?",a:"Allah'ın insanlara doğru yolu bildirmek üzere seçtiği elçidir.",langs:[]},
{n:28,q:"Hz. Muhammed kimdir?",a:"Allah'ın son peygamberi ve bütün insanlığa gönderilmiş elçisidir.",langs:[]},
{n:29,q:"Sünnete uymak neden önemlidir?",a:"Hz. Peygamber'in örnek hayatını takip etmek, İslam'ı doğru yaşamaya yardımcı olur.",langs:[]},
{n:30,q:"Ahlak nedir?",a:"İnsanın davranışlarını ve karakterini şekillendiren güzel veya kötü huy ve davranışlardır.",langs:[]},
{n:31,q:"Doğruluk neden önemlidir?",a:"Doğruluk güvenin temelidir ve İslam'ın önem verdiği güzel ahlaktan biridir.",langs:[]},
{n:32,q:"Kul hakkı nedir?",a:"Bir insanın diğer insanın malına, canına, onuruna veya hakkına haksız şekilde müdahale etmesidir.",langs:[]},
{n:33,q:"Anne babaya karşı görevler nelerdir?",a:"Onlara iyilik etmek, saygılı davranmak ve meşru konularda gönüllerini hoş tutmaya çalışmaktır.",langs:[]},
{n:34,q:"Komşuluk hakkı nedir?",a:"Komşuya zarar vermemek, gerektiğinde yardımcı olmak ve iyi ilişkiler kurmaktır.",langs:[]},
{n:35,q:"Sadaka nedir?",a:"Allah rızası için gönüllü olarak yapılan maddi veya manevi iyiliktir.",langs:[]},
{n:36,q:"Dua nedir?",a:"Kulun Allah'a yönelerek O'ndan istemesi, yardım dilemesi ve O'na yakarmasıdır.",langs:[]},
{n:37,q:"Tevekkül nedir?",a:"Gerekli sebeplere başvurduktan sonra sonucu Allah'a bırakıp O'na güvenmektir.",langs:[]},
{n:38,q:"Allah'a güvenmek ne demektir?",a:"Allah'ın kudretine ve yardımına güvenmek, O'nun hüküm ve hikmetine teslim olmaktır.",langs:[]},
{n:39,q:"İmanın şartları nelerdir?",a:"Allah’a, meleklerine, kitaplarına, peygamberlerine, âhiret gününe ve kadere inanmaktır.",langs:["The pillars of faith are belief in Allah, His angels, His books, His messengers, the Last Day and divine decree.","Die Glaubensgrundsätze sind der Glaube an Allah, Seine Engel, Seine Bücher, Seine Gesandten, den Jüngsten Tag und die göttliche Vorherbestimmung.","Основы веры — вера в Аллаха, Его ангелов, Его Писания, Его посланников, Судный день и предопределение.","Mercên îmanê bawerî bi Allah, milyaketên Wî, pirtûkên Wî, pêxemberên Wî, roja qiyametê û qederê ye.","Les piliers de la foi sont de croire en Allah, en Ses anges, en Ses Livres, en Ses messagers, au Jour dernier et au destin.","Los pilares de la fe son creer en Allah, en Sus ángeles, en Sus libros, en Sus mensajeros, en el Día del Juicio y en el destino.","أَرْكَانُ الْإِيمَانِ هِيَ الْإِيمَانُ بِاللَّهِ، وَمَلَائِكَتِهِ، وَكُتُبِهِ، وَرُسُلِهِ، وَالْيَوْمِ الْآخِرِ، وَالْقَدَرِ."]},
{n:40,q:"Allah’a iman ne demektir?",a:"Allah’ın varlığına ve birliğine, isim ve sıfatlarının mükemmelliğine inanmak demektir.",langs:[]},
{n:41,q:"Melekler kimdir?",a:"Melekler, Allah’ın nurdan yarattığı ve O’nun emirlerine itaat eden gaybî varlıklardır.",langs:[]},
{n:42,q:"Peygamberlere iman ne demektir?",a:"Allah’ın gönderdiği bütün peygamberlerin Allah’ın elçileri olduğuna ve getirdikleri vahyin hak olduğuna inanmaktır.",langs:[]},
{n:43,q:"Son peygamber kimdir?",a:"Son peygamber Hz. Muhammed’dir. Ondan sonra peygamber gelmeyecektir.",langs:[]},
{n:44,q:"Âhiret günü nedir?",a:"İnsanların öldükten sonra yeniden diriltileceği, hesaba çekileceği ve yaptıklarının karşılığını göreceği gündür.",langs:[]},
{n:45,q:"Kader nedir?",a:"Kader, Allah’ın her şeyi ezelî ilmiyle bilmesi ve her şeyi bir ölçü ve hikmet üzere takdir etmesidir.",langs:[]},
{n:46,q:"İslâm’ın şartları nelerdir?",a:"Kelime-i şehadet getirmek, namaz kılmak, zekât vermek, oruç tutmak ve gücü yetenin hacca gitmesidir.",langs:[]},
{n:47,q:"Zekât nedir?",a:"Zekât, dinen belirlenen şartları taşıyan maldan ihtiyaç sahiplerine verilmesi gereken farz bir mali ibadettir.",langs:[]},
{n:48,q:"Oruç nedir?",a:"Oruç, imsak vaktinden güneş batıncaya kadar Allah’ın rızası için yeme, içme ve orucu bozan şeylerden uzak durmaktır.",langs:[]},
{n:49,q:"Ramazan ayı neden önemlidir?",a:"Çünkü Kur’an’ın indirildiği, oruç tutulduğu ve ibadetlerin artırıldığı mübarek bir aydır.",langs:[]},
{n:50,q:"Hac nedir?",a:"Hac, gücü yeten Müslümanların belirli zamanda Kâbe’yi ve belirli yerleri usulüne uygun olarak ziyaret etmesidir.",langs:[]},
{n:51,q:"Kıble nedir?",a:"Kıble, Müslümanların namaz kılarken yöneldikleri Kâbe’nin bulunduğu yöndür.",langs:[]},
{n:52,q:"Kur’an’ın ilk emri nedir?",a:"Kur’an’ın ilk vahyinde “Oku!” emri gelmiştir.",langs:[]},
{n:53,q:"Müslüman ilim öğrenmeye neden önem vermelidir?",a:"Çünkü faydalı ilim insanın Allah’ı daha iyi tanımasına, doğruyu öğrenmesine ve hayatını doğru şekilde düzenlemesine yardımcı olur.",langs:[]},
{n:54,q:"Sabır nedir?",a:"Sabır, zorluklar karşısında Allah’a güvenerek doğru davranıştan ayrılmamak ve sıkıntılara dayanmak demektir.",langs:[]},
{n:55,q:"Şükür nedir?",a:"Şükür, Allah’ın nimetlerini bilmek, O’na teşekkür etmek ve nimetleri O’nun razı olduğu şekilde kullanmaktır.",langs:[]},
{n:56,q:"Tevbe nedir?",a:"Tevbe, günahtan vazgeçmek, pişman olmak, Allah’tan bağışlanma dilemek ve tekrar günaha dönmemeye karar vermektir.",langs:[]},
{n:57,q:"Müslüman affedici olmayı neden önemser?",a:"Çünkü affetmek güzel ahlâkın bir parçasıdır ve insanlar arasındaki kin ve düşmanlığın azalmasına yardımcı olur.",langs:[]},
{n:58,q:"Ayet ve hadisleri öğrenmek neden önemlidir?",a:"Dinî bilgilerin Kur’an ve sünnetle bağlantısını anlamaya yardımcı olur.",langs:[]},
{n:59,q:"İlmihal nedir?",a:"Müslümanın günlük hayatında ihtiyaç duyduğu temel dinî hükümleri açıklayan ilim ve eserler bütünüdür.",langs:[]},
{n:60,q:"Hanefî mezhebi nedir?",a:"Ehl-i Sünnet içinde yer alan ve İmam Ebû Hanîfe'nin usul ve görüşleri etrafında gelişen fıkıh mezhebidir.",langs:[]},
{n:61,q:"Ehl-i Sünnet ve'l-Cemaat ne demektir?",a:"Kur’an ve sünnete, sahabe ve ümmetin güvenilir ilmî mirasına bağlı itikadî ana çizgiyi ifade eder.",langs:[]},
{n:62,q:"İbadetlerde niyet neden önemlidir?",a:"İbadetin Allah rızası için yapıldığını belirler ve ibadetin değerini etkiler.",langs:[]},
{n:63,q:"Günahlardan korunmak için ne yapılmalıdır?",a:"Allah'ı hatırlamak, farzları yerine getirmek, haramlardan kaçınmak ve iyi çevre edinmek gerekir.",langs:[]},
{n:64,q:"Günah işleyen Müslüman ne yapmalıdır?",a:"Günahı terk etmeli, pişman olmalı, Allah'tan bağışlanma dilemeli ve mümkünse kul hakkını telafi etmelidir.",langs:[]},
{n:65,q:"İstiğfar nedir?",a:"Allah'tan günahların bağışlanmasını dilemektir.",langs:[]},
{n:66,q:"Sabır ile tevekkül arasındaki ilişki nedir?",a:"Sabır zorlukta sebat etmeyi, tevekkül ise gerekli sebeplere sarıldıktan sonra Allah'a güvenmeyi ifade eder.",langs:[]},
{n:67,q:"Şükür nasıl yapılır?",a:"Kalp ile nimeti Allah'tan bilmek, dil ile hamdetmek ve nimeti Allah'ın razı olduğu yerde kullanmakla yapılır.",langs:[]},
{n:68,q:"Affetmek her durumda gerekli midir?",a:"Affetmek güzel bir ahlaktır; ancak hakların korunması ve adaletin gözetilmesi de önemlidir.",langs:[]},
{n:69,q:"İslam'da adalet nedir?",a:"Herkese hakkını vermek ve ölçülü, tarafsız ve doğru davranmaktır.",langs:[]},
{n:70,q:"İslam'da merhamet nedir?",a:"İnsanlara ve canlılara şefkatle davranmak ve ihtiyaç sahiplerine yardım etmektir.",langs:[]},
{n:71,q:"Müslümanın dili nasıl olmalıdır?",a:"Doğru, temiz, faydalı ve insanları incitmekten uzak olmalıdır.",langs:[]},
{n:72,q:"Gıybet nedir?",a:"Bir kimsenin arkasından, duyduğunda hoşlanmayacağı bir özelliğini söylemektir.",langs:[]},
{n:73,q:"Yalan neden haramdır?",a:"Yalan güveni bozar ve İslam'ın emrettiği doğruluk ilkesine aykırıdır.",langs:[]},
{n:74,q:"İslam'da emanet nedir?",a:"Bir kimsenin korumak veya yerine getirmek üzere güvenerek bıraktığı hak ve sorumluluktur.",langs:[]},
{n:75,q:"İlim ile amel arasındaki ilişki nedir?",a:"Öğrenilen doğru bilginin hayata geçirilmesi ilmin faydasını ortaya çıkarır.",langs:[]},
{n:76,q:"Bir Müslüman dinini öğrenmeye nereden başlamalıdır?",a:"Önce iman esaslarını, temel ibadetleri, helal-haram bilgilerini ve güzel ahlakı güvenilir kaynaklardan öğrenmelidir.",langs:[]}
];
